fail_fast: false
repos:
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
      language_version: python3.6
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: debug-statements  # check for existence of pdb / ipdb/ pudb statements
      - id: flake8
        name: flake8
        entry: flake8
