# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 13:47
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('omni_wagtail_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryitemdetailpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock())), blank=True, null=True),
        ),
    ]
