# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('omni_wagtail_library', '0002_alter_streamfield_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitemdetailpage',
            name='teaser',
            field=models.CharField(blank=True, help_text='A short extract of text, to be displayed when this appears in a list', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='libraryitemdetailpage',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
